export const MEAL_TYPES = [
  { label: 'Breakfast', value: 'breakfast' },
  { label: 'Lunch', value: 'lunch' },
  { label: 'Dinner', value: 'dinner' },
  { label: 'Snack', value: 'snack' },
  { label: 'Pre-Workout', value: 'pre_workout' },
  { label: 'Post-Workout', value: 'post_workout' },
] as const;

export const COMMON_FOODS = [
  {
    id: '1',
    name: 'Chicken Breast',
    servingSize: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
  },
  {
    id: '2',
    name: 'Brown Rice',
    servingSize: 100,
    calories: 123,
    protein: 2.7,
    carbs: 25.6,
    fats: 1,
  },
  {
    id: '3',
    name: 'Salmon',
    servingSize: 100,
    calories: 208,
    protein: 20,
    carbs: 0,
    fats: 13,
  },
  {
    id: '4',
    name: 'Eggs',
    servingSize: 100,
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fats: 11,
  },
  {
    id: '5',
    name: 'Banana',
    servingSize: 100,
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fats: 0.3,
  },
  {
    id: '6',
    name: 'Oatmeal',
    servingSize: 100,
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fats: 6.9,
  },
  {
    id: '7',
    name: 'Greek Yogurt',
    servingSize: 100,
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fats: 0.7,
  },
  {
    id: '8',
    name: 'Sweet Potato',
    servingSize: 100,
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fats: 0.1,
  },
];